
CREATE DATABASE NYPD_Arrests_Data_Staging;

USE NYPD_Arrests_Data_Staging;

CREATE TABLE NYPD_Arrests_Staging(
	ARREST_KEY INT NOT NULL,
	ARREST_DATE DATE,
	PD_CD INT,
	PD_DESC VARCHAR(200),
	KY_CD INT,
	OFNS_DESC VARCHAR(200),
	LAW_CODE VARCHAR(100),
	LAW_CAT_CD VARCHAR(10),
	ARREST_BORO VARCHAR(10),
	ARREST_PRECINCT INT,
	JURISDICTION_CODE INT,
	AGE_GROUP VARCHAR(50),
	PERP_SEX VARCHAR(10),
	PERP_RACE VARCHAR(50),
	X_COORD_CD int,
	Y_COORD_CD int,
	LATITUDE VARCHAR(100),
	LONGITUDE VARCHAR(100),
	LON_LAT VARCHAR(500)
	PRIMARY KEY(ARREST_KEY)
);

